def add_home_planet(dataset):
    """
    This function assigns a HomePlanet to specific passengers.
    The chosen planet for each passenger is determined based on whether they share a cabin with another person.
    In this way, we avoid assigning a random home planet,
    relying instead on a hypothesis that will be tested in a later stage of the project development.
    """
    dataset.loc[dataset['PassengerId'] == '2404_04', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '2505_01', 'HomePlanet'] = 'Earth'
    dataset.loc[dataset['PassengerId'] == '2506_01', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '2597_02', 'HomePlanet'] = 'Mars'
    dataset.loc[dataset['PassengerId'] == '2730_01', 'HomePlanet'] = 'Earth'
    dataset.loc[dataset['PassengerId'] == '2799_02', 'HomePlanet'] = 'Earth'
    dataset.loc[dataset['PassengerId'] == '2822_01', 'HomePlanet'] = 'Earth'
    dataset.loc[dataset['PassengerId'] == '2822_05', 'HomePlanet'] = 'Earth'
    dataset.loc[dataset['PassengerId'] == '3131_03', 'HomePlanet'] = 'Earth'
    dataset.loc[dataset['PassengerId'] == '3439_03', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '3703_01', 'HomePlanet'] = 'Mars'
    dataset.loc[dataset['PassengerId'] == '4030_01', 'HomePlanet'] = 'Earth'
    dataset.loc[dataset['PassengerId'] == '4172_03', 'HomePlanet'] = 'Mars'
    dataset.loc[dataset['PassengerId'] == '4207_01', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '4216_02', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '4371_03', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '4625_06', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '4655_02', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '4822_03', 'HomePlanet'] = 'Mars'
    dataset.loc[dataset['PassengerId'] == '4933_02', 'HomePlanet'] = 'Mars'
    dataset.loc[dataset['PassengerId'] == '5090_03', 'HomePlanet'] = 'Earth'
    dataset.loc[dataset['PassengerId'] == '5367_02', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '5427_01', 'HomePlanet'] = 'Mars'
    dataset.loc[dataset['PassengerId'] == '5465_02', 'HomePlanet'] = 'Mars'
    dataset.loc[dataset['PassengerId'] == '5684_01', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '5981_02', 'HomePlanet'] = 'Mars'
    dataset.loc[dataset['PassengerId'] == '6036_02', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '6263_02', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '6313_02', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '6363_02', 'HomePlanet'] = 'Earth'
    dataset.loc[dataset['PassengerId'] == '6402_05', 'HomePlanet'] = 'Earth'
    dataset.loc[dataset['PassengerId'] == '6490_04', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '6512_02', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '6561_02', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '6810_04', 'HomePlanet'] = 'Mars'
    dataset.loc[dataset['PassengerId'] == '6954_02', 'HomePlanet'] = 'Mars'
    dataset.loc[dataset['PassengerId'] == '6992_01', 'HomePlanet'] = 'Earth'
    dataset.loc[dataset['PassengerId'] == '7104_01', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '7584_03', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '7584_01', 'Destination'] = 'TRAPPIST-1e'
    dataset.loc[dataset['PassengerId'] == '7703_02', 'HomePlanet'] = 'Earth'
    dataset.loc[dataset['PassengerId'] == '7790_01', 'HomePlanet'] = 'Mars'
    dataset.loc[dataset['PassengerId'] == '7830_04', 'HomePlanet'] = 'Earth'
    dataset.loc[dataset['PassengerId'] == '7853_01', 'HomePlanet'] = 'Mars'
    dataset.loc[dataset['PassengerId'] == '7873_01', 'HomePlanet'] = 'Earth'
    dataset.loc[dataset['PassengerId'] == '7950_01', 'HomePlanet'] = 'Earth'
    dataset.loc[dataset['PassengerId'] == '8202_03', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '8314_02', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '8637_01', 'HomePlanet'] = 'Mars'
    dataset.loc[dataset['PassengerId'] == '8816_02', 'HomePlanet'] = 'Europa'
    dataset.loc[dataset['PassengerId'] == '8860_02', 'HomePlanet'] = 'Mars'
    dataset.loc[dataset['PassengerId'] == '8938_01', 'HomePlanet'] = 'Mars'
    dataset.loc[dataset['PassengerId'] == '9072_01', 'HomePlanet'] = 'Mars'
    dataset.loc[dataset['PassengerId'] == '9194_01', 'HomePlanet'] = 'Europa'

    return dataset
